<?php

namespace AppBundle\Repository;

/**
 * PersonPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonPhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
