<?php

namespace AppBundle\Repository;

/**
 * ShipOrderToRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipOrderToRepository extends \Doctrine\ORM\EntityRepository
{
}
