<?php

namespace AppBundle\Repository;

/**
 * ShipOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
